#!/bin/bash

curl -L https://istio.io/downloadIstio | sh -
cd istio-1.6.2
export PATH=$PWD/bin:$PATH
istioctl install --set profile=demo
kubectl label namespace default istio-injection=enabled

# Check all Istio pods have STATUS 'Running'
# kubectl get pods -n istio-system
